- alias: 'Front Lights Off at Sunrise'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id:
      - light.garage_left
      - light.garage_right
      - light.porch_left
      - light.porch_right

- alias: 'Front Lights On at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: light.turn_on
      entity_id:
        - light.garage_left
        - light.garage_right
    - service: light.turn_on
      entity_id:
        - light.porch_left
        - light.porch_right
      data:
        rgb_color: [255, 0, 0]
        brightness_pct: 100

- alias: 'Jeopardy Time'
  trigger:
    platform: time
    at: '18:58:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_on
    entity_id: script.rec_room_jeopardy

- alias: 'Jeopardy Off'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_off
    entity_id: script.rec_room_jeopardy


- alias: 'Set Radio Volume'
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Office") %} media_player.office_speaker
        {% elif is_state("input_select.chromecast_radio", "Great Room") %} media_player.great_room_speaker
        {% elif is_state("input_select.chromecast_radio", "Whole Home") %} media_player.whole_home
        {% elif is_state("input_select.chromecast_radio", "Master Bedroom") %} media_player.master_bedroom_speaker
        {% elif is_state("input_select.chromecast_radio", "Rec Room") %} media_player.rec_room_speaker
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'
