- alias: 'Front Lights Off at Sunrise'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id:
      - light.garage_left
      - light.garage_right
      - light.porch_left
      - light.porch_right

- alias: 'Front Lights On at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: light.turn_on
      entity_id:
        - light.garage_left
        - light.garage_right
    - service: light.turn_on
      entity_id:
        - light.porch_left
        - light.porch_right
      data:
        rgb_color: [255, 0, 0]
        brightness_pct: 100

- alias: 'Jeopardy and Wheel of Fortune'
  trigger:
    platform: time
    at: '18:59:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_on
    entity_id: script.jeopardy_and_wheel

- alias: 'Bedtime for the Boys'
  trigger:
    platform: time
    at: '20:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.whole_home
        volume_level: '0.5'
    - service: tts.google_say
      data:
        entity_id: media_player.whole_home
        message: 'Hunter and Tyler it is time for you to brush your teeth and take a
        bath before you go to bed. If you are good and cooperate with mommy and daddy
        then maybe there will be a treat waiting for you when you are done with your
        bath. And remember, Go Lions!'
